### ISSUE TITLE
AddStats Copy changes

### ISSUE THREAD

**Issue by maxgerber** [InFact-coop/LCN#143]
**Issue**: Multiple snippets of copy in the AddStats view need revising for clarity in accordance with user feedback

### Reception/Triage

* **Feedback**: This user felt that the term "Law Centre advice" was ambiguous, as it could refer to either internal or external law centres.

  **Feedback**: They felt that the word "referred" was inappropriate for reception/triage questions, as it suggested a more formal process.
  
  **Feedback**: The checklist of "Types of agencies referred to" was non-exhaustive. "Local" might refer to within-borough, or within-city.
  
  **Feedback**: The client also suggested "Local solicitor" as another checklist option.
  
 - [ ] **Proposal 1**: Double check receptionist/triage copy for points of ambiguity like this, and clarify them according to suggestions from our user base.

 - [ ] **Proposal 2**: Add an extra numerical question: "Of those enquiries, how many people were either taken on or given an appointment by your law centre?"

### Management

* **Feedback**: For this user, the total amount of vounteers is not clearly summarised as "student", "non-student", and "lawyer". Some students are studying to be lawyers, for example, some volunteers do admin, and some might have other miscellaneous roles.

* **Feedback**: The question about "media coverage" does not fit the expected format for a numerical answer.

* **Feedback**: The vacancies question could refer to trustees, but it should just refer to "staff".

 - [ ] **Proposal 3**: Double check management copy for points of ambiguity like this, and clarify them according to suggestions from our user base.

### Lawyer/Caseworker (Employment law)

* **Feedback**: The term "client matters" could be ambiguous, as some people who work at law centres might do outreach work outside of their law centre - for example, working in employment centres for some of the week.

  **Feedback**: The word "problems" is both ambiguous and potentially leading.
  
  **Feedback**: This user would have been happy to have narrowed down the checklist point "Discrimination" to expand on different types of discrimination.
  
  **Feedback**: "Constructive dismissal" might also be an appropriate point to put in.
  
- [x] **Proposal 4**: Double check all lawyer/caseworker copy for points of ambiguity like this, and clarify them according to suggestions from our user base.

### Lawyer/Caseworker (Welfare)

- [x] **Proposal 5**: We could add "Carers' allowance" to checklist

**Comment by NB76** [comment]
My Add Stats view has changed a little and seems to include all three staff categories: management, reception and (benefits) caseworkers. Is this just temporary as it's being worked on? 

I also cannot change my settings or reset my password, so I'm working again only with what I can see.

Regardless, where a person is in more than one category, the respective questions need to be clearly distinguished. At the moment, I can't readily tell where one starts and the other begins. 

Following the onboarding text, we don't need a long intro blurb as currently, so instead have:
"Please tell us a little about your week since the last time you checked in." 

Clarifications: 

- Caseworker/Welfare: yes, please add Carers' Allowance

- Caseworker/Employment; yes, please add 'constructive dismissal'. Refer to 'cases (including those of returning clients' rather than 'matters'. Refer to 'legal issues' rather than 'problems'. Not that many people do discrimination cases so for the moment let's go with just 'discrimination' and if there is enough volume we could expand to direct/indirect/disability/ethnicity/sex/faith... 

- Management: refer to 'staff vacancies' rather than just vacancies. Ask 'how many media stories has your Law Centre had this week, if any?' rather than current wording. On volunteers, ask about total, of which law students, or of which lawyers; we're asking about grouping, not role. 

- Reception: rather than proposal 2, have "how many were taken on by the Law Centre/given an appointment?" (the 'or' there is paraphrasing, not two separate options). Rather than 'Law Centre advice', ask "how many were signposted to one-off advice at the Law Centre (e.g. advice line, drop-in or pro bono clinics, where available)"
