### ISSUE TITLE
Left todo

### ISSUE THREAD

**Issue by ivanmauricio** [InFact-coop/LCN#74]
# LCN todo
## Functionality
- [x] Write script for user testing session

## Mocked up
- [x] Like comments increment
- [x] Disable like button after user has pressed it once

## Copy
- [x] Update copy that @Nimrod sent through @ivanmauricio
- [x] Put links on logout page

## Done
- [x] Sort out font hierarchy @ivanmauricio
- [x] Standardise button styles across all views
- [x] Add comma to number of people seen
- [x] If 'No Area' is selected then all requests fail @ivanmauricio
- [x] Disable submit button on qual form until comment body has been inputted
- [x] Disable login button until they have filled in fields
- [x] Ask Nimrod for links that should go onto log out page
- [x] Show other buttons as disabled when on a particular topic in qual form
- [x] Get copy from @Nimrod for the summary page 
- [x] Change comment colours depending on the comment type
- [x] Links on navbar bigger
- [x] Style reply-to text input functionality
- [x] Fill out rest of lawCentres both in Elm and Airtable
- [x] Style normal comments
- [x] Fill in rest of lawAreas both in Elm and Airtable
- [x] Style replied to comments
- [x] Rename `case worker` to `lawyer/case worker`
- [x] Qual form modal
- [x] Get copy and questions from @Nimrod for forms for different roles and areas of law
- [x] Reply to comment functionality
- [x] Add home link to logo
- [x] Put createdAt field in comments
- [x] Get rid of modal on replying to comment
